FROM node:18-alpine AS builder
WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

ENV REACT_APP_BACKEND_URL=/api

RUN npm run build

FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]