services:
  # 1. Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres_game_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend Python/Flask (Balanceado e sem porta externa)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_NAME=postgres
      - FLASK_DB_PASSWORD=secretpass
      - FLASK_DB_HOST=postgres
      - FLASK_DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 2 # Inicia duas instâncias para o NGINX balancear a carga

  # 3. Frontend React e Proxy NGINX
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nginx_react_proxy
    ports:
      - "8080:80" # Única porta exposta para o usuário acessar a aplicação
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

# Declaração do volume nomeado para persistência de dados
volumes:
  postgres_data:
