FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN sed -i 's/\r$//' start-backend.sh && chmod +x start-backend.sh

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]