# O bloco upstream agrupa seus containers do backend
upstream flask_backend {
    server backend:5000;
}

server {
    listen 80;
    server_name localhost;

    # 1. Rotas da API (Flask)
    # Qualquer requisição que comece com /create ou /guess/ será enviada ao backend
    location ~ ^/(create|guess/.*) {
        proxy_pass http://flask_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Rotas do Frontend (React/SPA)
    # Serve os arquivos estáticos e redireciona rotas não encontradas para o index.html
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}